### ISSUE TITLE
Double tab to live area bug

### ISSUE THREAD

**Issue by GrayJack** [TheOfficialFloW/Adrenaline#1]
When Adrenaline is used in a created PSP mini bubble (ePSP Bubble Installer) the feature doesn't work

**Comment by szczuru** [comment]
Same here on Vita 1k- as base i've used Adrenaline Easy Installer (that one which installs Adrenaline v2 then replaced v2 files with v3).

**Comment by iamn0tdev** [comment]
It seems to be a compatibility issue with the base game used. I got application not found with **echochrome** as a base game, but it is working fine with **Ape Quest**.

**Comment by hyln9** [comment]
I believe it's a bug of easy_installer instead of adrenaline.
Uninstall adrenaline from easy_installer and do a manual install will fix this problem.

**Comment by GrayJack** [comment]
I never used the easy installer before, so it's not the easy installer

**Comment by iamn0tdev** [comment]
@hyln9 @GrayJack So the real issue is a conflict created by the Easy Installer (PBOOT.PBP ?) I used EI to install adrenaline with echochrome, but manual installed with Ape Quest. Now echocrome as a base game its working fine because I deleted everything related to EI from the game. I can double tap to live area.

**Comment by GrayJack** [comment]
It seen that the problem was indeed the Easy Installer, so, I'm closing this issue

**Comment by fennectech** [comment]
Is there a workarround to enable the use of pboot.pbp or another way to alter the bubbles appearece

**Comment by CelesteBlue-dev** [comment]
Problem source found by Chihiro :
The problem is caused by Adrenaline Easy Installer, by PBOOT.PBP it copies, by PARAM.SFO inside,  by DISC_ID not being the same than BASEGAME's TITLEID.

Solution(s) :
- Wait for Adrenaline Easy Installer update,
- Patch DISC_ID manually :
Download latest AdrenalineEasyInstaller.vpk.
Extract it using 7Zip or equivalent software.
Open files/PBOOT.PBP with PBP Unpacker v0.94.
Open PARAM.SFO.
Change DISC_ID to your BASEGAME's TITLEID.

**Comment by TheOfficialFloW** [comment]
Fixed https://github.com/TheOfficialFloW/Adrenaline/commit/f99d5a5189b63a9d8b55a0fac3eb6186b3a97c87

**Comment by CelesteBlue-dev** [comment]
Lol I did that comment for nothing ! 😂

**Comment by fennectech** [comment]
CelesteBlue-dev  your method does not work  but i found a method that DOES work   you need to open the pboot.pbp in an hex editor and replace the launcher with your titleid making sure the filesize remains the same  (use overwrite instaid of insert mode wich is the "ins" key)

**Comment by fennectech** [comment]
https://gyazo.com/f441843edf59a445cb30628df3558331  Here is what i did for half minute hero evil dead demo!
