### ISSUE TITLE
Uma partition for adrenalina

### ISSUE THREAD

**Issue by magpte** [TheOfficialFloW/Adrenaline#109]
Thanks for all the hardwork for PSV. As the sd2vita is online recently, is it possible to add up uma partition for adrenaline?

**Comment by sonofskywalker3** [comment]
I can second this. Might take a look at the code myself, though I haven't done C in years.

**Comment by sorgelig** [comment]
Also vote for this. It's one of important feature for sd2vite users.
I've tried to compile by myself but buried in dependencies. Would be good t have instruction how to build it together with links to all dependencies (vita2d is not enough. Shaders libs are too wild in compiling).

**Comment by sonofskywalker3** [comment]
yes, I am at the same point. Got the Kernel to build, but not the user, missing dependencies. And I know even less about compiling than I do about coding, since most of my experience has been in html or visual studio...

**Comment by chaoskagami** [comment]
I did a quick hack the other day, so I can help. There's a few instances of ux0: peppered throughout; the important one is returned from a path builder function based on the currently selected device. It's in a switch statement. For a quick hack, change that one. I don't have the code in front of me, so I can't tell you exactly where.

This is also leaving aside the usb mount function. You can probably adapt this by fixing up the relevant string, but we've entered a whole new world of hurt where devices and mountpoints can be mismatched, so this isn't a proper solution.

As for building - see that link in the bottom of the readme? You need to build it from the 'fbo' branch, not master, and install. You're then going to hit an error about some missing library; this is in the samples directory of the linked repo (it's a static library) - copy it to `vitasdk/arm-vita-eabi/lib`. You need to build kernel, then user. You can stop there if you'd like since you only need the skprx and suprx for this.

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/Adrenaline/commit/f4c394f8f70fa8b4d50d26df1b93edcb968d38b3
Will be available in the next update.
