### ISSUE TITLE
Adrenaline on SD2VITA - Error. Has anyone managed to install/run?

### ISSUE THREAD

**Issue by juan9999** [TheOfficialFloW/Adrenaline#124]
I just did the new offline activation but can't get Adrenaline to work on SD2VITA

I did a complete wipe and reinstall and found that the issue seems to be related to Adrenaline on SD2VITA

Here is what I did

1. Uninstall enso. Vita may ask you to format your card, don’t do it now.
2. Restore system. ENTER SAFE MODE Restore this system. 
3. During first launch select “I have PSN account” and “Login later”
4. Format memory cards (internal and external)
5. Install Henkaku.
6. Install enso.
7. Install MLActivator and run it. After system reboot open trophy app, just as MLActivator asks you.
8. Install ePSP Bundle installer and Adrenaline EasyInstaller, create bubble and install adrenaline into it.
9. Complete adrenaline installation during it’s first launch.

Here it ran fine, so then I tried to enable SD2VITA

10. Copy external memory card to SD2VITA
11. Enable SD2VITA as main memory
Here is where it stopped and gave a black screen with error C1-2858-3.

I switched back the config by commenting out the loading of gamesd.skprx and rebooted to run off the vita external memory, and adrenaline would not run and gave me the same error as before.

Anyone have a solution?

**Comment by FinnYoung** [comment]
i have the similar problem.

i have PSTV with enso and external hard drive used as sytem storage.
PSTV is activated. I use Ape Quest as a target for adrenaline (game starts with no issues).
I used latest adrenaline easy installer. after reboot i get C1-2858-3
i'll appreciate any advise how to solve this problem.

re Adrenaline on SD2VITA - i have activated vita with the same game, enso and sd2vita. adrenaline work with no issues.

**Comment by FinnYoung** [comment]
it's config issue.

make sure that in ur0:tai/config.txt you have:
```
*KERNEL
ur0:/tai/gamesd.skprx
ux0:adrenaline/adrenaline.skprx
```
in the end of this file you need to add:
```
*NPEG00005
ux0:adrenaline/adrenaline.suprx
```
where `NPEG00005` is your game id.
you can find your game id in `ux0:tai/config.txt`

after making these changes to your `ur0:tai/config.txt` remove `config.txt` from `ux0:tai` and reboot.

**Comment by juan9999** [comment]
Thanks, that’s correct.

I think my config got corrupted when I disabled SD2VITA or ejected the sony external memory.

**Comment by razorbcn** [comment]
@FinnYoung tried that config, even having adrenaline folder at ur0 and changing config and point to ur0 and still getting the error C1-2858-3

**Comment by FinnYoung** [comment]
@razorbcn i'm not 100% sure, but i think this error may happen if your vita/pstv doesn't load adrenaline plugins correctly.

your adrenaline folder should not be at ur0. it should be at `ux0` (microSD/hardDrive/flashCard).

1) if you use the same setup as me or **juan9999** - enso, vita (or pstv) with microSD or hard drive, make sure that your microSD visible as `ux0` after restart.
2) next thing you need ensure - you can start your psone/demo game without adrenaline
3) install adrenaline with `Adrenaline EasyInstaller`. latest version was 1.15. 
4) make sure that in `ur0:tai/config.txt` in `*KERNEL` section you have `ux0:adrenaline/adrenaline.skprx` going after `ur0:/tai/[YOUR_SD_OR_HARD_DRIVE_PLUGIN_NAME]`
5) in the end of `ur0:tai/config.txt` you need to have:
```
*YOURGAMEID
ux0:adrenaline/adrenaline.suprx
```
where `YOURGAMEID` - your psone game id. after installing game with `Adrenaline EasyInstaller` you should have these lines at `ux0:tai/config.txt` after installing adrenaline with `Adrenaline EasyInstaller`. it just adds these lines automatically

double/triple-check that you have no typos and right file locations at your `ur0:tai/config.txt`
6) your  `ux0:tai` folder should be empty.

if it's still not work for you - post you `ur0:tai/config.txt` here, file list from `ur0:tai` and file list from `ux0:tai`. mb i'll be able to find something obvious.

**Comment by Laddyacris** [comment]
Hello 
I've the same error , I have a ps vita henkaku enso with true PSN with sd2vita 128 Go scandisk and no sony memory card. 
I followed instructions without success ;(

**Comment by 6thsurvivor** [comment]
@FinnYoung I have the same problem here, with the config being identical to yours, with ux0:/tai empty and ur0 having only the adrenaline and sd driver plugin files. 
Some forums suggest moving the adrenaline plugin to ur0 and changing the path in config file to run it from there, but that didn't work for me. 

I think the issue here could be between the sd2vita driver (I'm using the one mounting the Sony card as uma) and the sd as ux0) and the ePHP bubble installer - before stupidly deleting my sony card, I ran Adrenaline using the Ape Escape demo. 
Now, I'm force to use the custom bubble (no qcma backup and copy from ps3 is blocked by sony changes) and it just boots into the minis logo -> C1-2858-3 Error. 
@Laddyacris @razorbcn @juan9999 - could you guys tell us what driver are you using and are you all running adrenaline from an ePSP bubble?

**Comment by FinnYoung** [comment]
@6thsurvivor i use driver provided by some plugin which switch official sony memory card and microSD. but after setting microSD as ux0 by this plugin i made manual changes to `ur0:tai/config.txt`. i don't remember why i used this plugin instead of normal `gamesd` plugin.

re bubble installer - never used it. but in theory if you have some demo/psmini at your ps3 - you can try to copy it to qcma. i copied ape quest from qcma to pstv just couple of days ago. so i suppose it should be possible to copy some game from ps3 to qcma and from qcma to vita/pstv. just use `vitaupdateblocker`. it still works.

from my experience - if psone game starts on vita without adrenaline, but adrenaline gives C1-2858-3 error, it means that you have bad `ur0:tai/config.txt`. or something in `ux0:tai` prevents adrenaline from loading

**Comment by 6thsurvivor** [comment]
@FinnYoung talk about strange - I can't copy from ps3 because i get E-80558325 after selecting the file - my ps3 is using the latest FW. What method did you use? Or did you mean copying it from the qcma library on the pc - in this case I didn't make one.

Regarding the configs, look at this: 

`ur0:tai/config.txt`
> \# For users plugins, you must refresh taiHEN from HENkaku Settings for
> \# changes to take place.
> \# For kernel plugins, you must reboot for changes to take place.
> *KERNEL
> \# henkaku.skprx is hard-coded to load and is not listed here
> ur0:tai/gamesd.skprx
> ux0:adrenaline/adrenaline.skprx
> *main
> \# main is a special titleid for SceShell
> ur0:tai/henkaku.suprx
> *NPXS10015
> \# this is for modifying the version string
> ur0:tai/henkaku.suprx
> *NPXS10016
> \# this is for modifying the version string in settings widget
> ur0:tai/henkaku.suprx
> *NPEZ00104
> ux0:adrenaline/adrenaline.suprx`
 
`ux0:tai`
> empty dir

`ur0:tai`
> config.txt
> taihen.skprx
> henkaku_config.bin
> henkaku.suprx
> henkaku.skprx
> gamesd.skprx
> boot_config.txt

**Comment by FinnYoung** [comment]
@6thsurvivor my bad. i forgot that ps3 doesn't have content manager. 
i copied psone game from PC(qcma) to pstv through wifi using VitaActivationBlocker's proxy. but i put this game to PC long time ago making backup from vita.

your config and everything else looks fine (except single quote after `adrenaline.suprx`, but i suppose it's markdown formatting issues and it's not a part of your config)
one thing worth double checking - that `NPEZ00104` is your game id.

i recommend you to uninstall adrenaline (using easy adrenaline installer), try to start your game. if game starts without any errors (or doing nothing if this game was installed using epsp bubble installer) - try to reinstall adrenaline.
if you get some errors - it may be activation problem.

if it's activation problem - you have 2 options:

1) use MTLActivator. some people using it, but using this software you have a high risk of getting ban from sony. if you going to go with this option:

_(note: use this instruction at your own risk. i don't take any responsibility for results received after going through these steps. this is just a way i would do that)_

a) remove bubble previously created by bubble installer
a_1) make sure that your sd card recognised as ux0 in molecular shell after reboot
a_2) install enso if you still don't have it
a_3) repeat a_1
b) install these files (before installing delete their bubbles if you have older versions):
`MTLActivatorFIX2.vpk`
`ePSP_Bubble_Installer_v3.1.vpk`
`AdrenalineEasyInstaller_v115.vpk`
c) activate your vita using MTLActivator
d) create bubble
e) install adrenaline
f) fix your config.txt (if required) and cleanup `ux0:tai`
g) if you still can't run adrenaline -> 2)

2) wait ~1 month (or less) for adrenaline which will not require activation. if i remember correctly it should be released at september.

**Comment by 6thsurvivor** [comment]
@FinnYoung yeah, it's a markdown issue - I changed the formatting. 
GameID is fine - it was addes by the Adrenaline easy installer. The 'game' boots fine without adrenaline (it's only a bubble so no game there, it shows the ps minis logo and exits). 

As for activation - my console is activated and I don't want to screw with mtla activator.
I'll try swapping the mountpoints (so sony card is the ux) to check if it works from the sony card. If it works from it, maybe it's a unknown DRM issue (magic gate emulation?)? 
Or just wait for the new release.. 

@TheOfficialFloW - does a 'debug build' of adrenaline plugin exists somewhere in your archives? Or is there a way to check did both plugins load at startup?

**Comment by FinnYoung** [comment]
@6thsurvivor try gamesd file from this plugin https://github.com/Applelo/SwitchSD2Vita
i took mine from there. after installing this plugin you should see 2 new files in ur:tai
one of them will have name gamesd_[something]
rename gamesd_[something] file from this plugin to gamesd, reboot and try run adrenaline again

i use gamesd.skprx from there. mb official skprx and skprx from this repo are different. but worth trying IMO

**Comment by TheOfficialFloW** [comment]
New Adrenaline will still need to load modules from config.txt

**Comment by 6thsurvivor** [comment]
@FinnYoung I managed to run it. I pulled out sd2vita, installed easy installer, and behold, it worked.
In vitashell, I spotted a tai folder in my ux0: - whic shouldn't be there since the ux0 was uma0 before, and it even had a sd2vita module inside (it was my backup from the sd2vita card..) 
What I did - after confirming that adrenaline was working, I put it on ur0 and confirmed that all paths in config.txt lead to ur0. 
After confirming adrenaline working, I removed ux0 tai catalog (remember this is the sony card so it will be uma0), uncommented the sd2vita driver, rebooted aaaand... after copyingt the 661.pbp to the right memory card.. it works.

**conclusion** 
It seems that the tai/ directory placed on uma0 is used during boot (maybe henkaku uses it before loading the driver?) and by having it there you will have a very bad time. Thanks for the tips @FinnYoung

**Comment by TheRealBlitze** [comment]
After installing enso I experienced that I receive the same error but im not using sd2vita just the standard Sony SD card ux0 and ur0 both have a tai folder but the one in ux0 contains only a config file

**Comment by TheOfficialFloW** [comment]
Should now work with https://github.com/TheOfficialFloW/Adrenaline/commit/f61187a4cdb71f52edff6454ccb6a6f45cf77fc9

**Comment by bustyouup4free** [comment]
just FYI guys... i installed it with the adrenaline.vpk and it installs to app/PSPEMUCFW/

make sure u add that path instead if you installed adrenaline with the vpk
