### ISSUE TITLE
Adrenaline needs to be opened twice in order for it to run.

### ISSUE THREAD

**Issue by cvskid** [TheOfficialFloW/Adrenaline#132]
The new adrenaline update v6 works great. After installing though whenever i reboot or shutdown my ps vita, i have to open adrenaline twice in order for it to load up. Is there something that can help to fix it so you only have to open adrenaline once after installing it to run it?

**Comment by TheOfficialFloW** [comment]
Did you read the readme???

**Comment by mathieulh** [comment]
This is because adrenaline must load its skprx before running if it hasn't been loaded before. You can mitigate this issue by adding a path to the skprx in you config.txt file (under *KERNEL). One way to work around this would be to use another (hidden) app to respawn the adrenaline app after it loads the skprx and closes when the skprx is not loaded. I am not sure someone will bother write this "fix".

**Comment by lunalik2** [comment]
Has this issue been fixed yet?
