### ISSUE TITLE
PSX compatibility issue

### ISSUE THREAD

**Issue by loginwall** [TheOfficialFloW/Adrenaline#155]
I have been trying to load FFVIII (SLUS00892) which works without issue on my PSP but the game seems to hangup before loading the title screen with the opening credits in Adrenaline. 

It's an all in one multple disc eboot, I originally wanted to test to see if Adrenaline even supports this functionality but at this point I can't even test the game to confirm whether or not it does.

**Comment by IcySon55** [comment]
I've been playing that game without issues for a while, your EBOOT might be bad.

**Comment by loginwall** [comment]
It most certainly isn't bad at all if it works on my PSP. If your copy isn't an all in one multidisc eboot, then it wouldn't surprise me if you got it to work.

**Comment by IcySon55** [comment]
It is an all-in-one eboot and works flawlessly.

**Comment by loginwall** [comment]
Did the Adrenaline PSXemu menu settings screen include the disc selection? I'd expect it to since this is how I switch discs on the PSP. Or do you switch discs via other means? There's quite a few possibilities to consider but again, considering that my PSP hasn't had any issues with this game at all I may have to just accept that adrenaline can't get it to run.

**Comment by gensosuikoden** [comment]
As you say you are just getting a hang rather than an error code,  I am assuming it is not an official PS Store eboot but just in case it is, it will work if you have the .rif license file. That would mean copying the game to PC from PSP via QCMA backup manager and then transferring to Vita. Otherwise, read on:

Adrenaline has issues with games that are not compatible with the stock version of pops. Dark Alex's popsloader utility work around cannot be ported to Adrenaline apparently. However, in my experience, there is one work-around for games that can't make it past pops on Adrenaline though. That work-around is Compression. If the ISO to Eboot conversion (via psx2psp or icetea or what have you) utilises compression, then game will load. Or at least that was the case with all 4 games I was having problems with. Converting the iso or bin/cue into a new eboot with just level 1 compression allowed the games to run. I can't quite recall but I think there was also one game that was already in compressed form as a CSO rather than ISO and converting that directly into eboot without further added compression seemed to work fine too but I could be misremembering that one.

There are possible downsides to compression if you want to go that route but I'll leave you to look into that yourself. You could also try PCSX Rearmed via Retroarch for Vita if Adrenaline doesn't work out for you.
