### ISSUE TITLE
[Feature Request] Enable "Smooth Graphics" with "Sharp Bilinear Without Scanlines"

### ISSUE THREAD

**Issue by TJF588** [TheOfficialFloW/Adrenaline#394]
While I notice a difference between "Smooth Graphics: On/Off" in conjunction with "Sharp Bilinear", "Sharp Bilinear Without Scanlines" seems to maintain roughness regardless of the "Smooth Graphics" setting. Could the smoothing feature be added to this filter setting?

**Comment by rsn8887** [comment]
Keep smooth graphics always on with the “sharp bilinear without scanlines” filter.

If you want smoothing, set the scale_x and scale_y to 1.995 instead of 2.000.

The whole idea of sharp-bilinear-without-scanlines is to give perfectly sharp pixels when the scaling is integer. It only uses the minimum amount of blur necessary when scaling is non-integer.

**Comment by rsn8887** [comment]
More information on the shader is here:
https://github.com/rsn8887/Sharp-Bilinear-Shaders

**Comment by pthfdr-42** [comment]
Seriously, as I commented before, you should support custom ".cg", ".cgp" and ".filter" files instead of presets.
