### ISSUE TITLE
Live area bubble for Psp games for convenience

### ISSUE THREAD

**Issue by asb64** [TheOfficialFloW/Adrenaline#405]
Feature request

**Comment by LoVega1337** [comment]
There's already something what you need: 
https://github.com/ONElua/AdrenalineBubbleManager/releases

**Comment by pstv-1** [comment]
I'll second this feature request - if only because the current situation is not user-friendly at all. Right now we need three homebrew apps (maintained by three different people) to replicate the *default behavior* of launching a PSP or PS1 Classic game from a bubble on the main screen:

1. download/update adrenaline to the latest version
2. check leecherman's page to see if adrbubblebooter has been updated for the current adrenaline release. if it hasn't - wait. (ignore the plugin version because that apparently no longer works with current adrenaline)
3. use the other homebrew mentioned above (or another way) to (re)create the bubbles in app.db. if you rebuild the database from the recovery menu you'll need to repeat whatever process you use.

It would be really great if Adrenaline handled this by itself allowing users two ways of playing their games - using the classic PSP experience and by (natively) supporting the faster direct bubble launching.

Specifically:
+ merge / replicate the base functionality used by leecherman (launch a game by passing the desired TITLE_ID to adrenaline via an app.db entry)
+ remember the last settings used for the game (under XMB) and re-use those settings when detecting the same TITLE_ID being passed to adrenaline from a bubble
+ scan for new/changed/removed PSP/PS1 games when launching adrenaline (this could be a 'Scan for content changes' option under adrenaline settings). if a game doesn't already have an entry in app.db (read: official PSP/PS1 bubbles from the store) extract the icon/info/meta and add the required entry so that it may be launched from a bubble after the next reboot (checking first for official bubbles will prevent adding duplicates of the same game). lastly, remove any orphan (adrenaline bubble) entries from app.db (in case the where the game has been removed/renamed) 

Thank you for Adrenaline! (and thanks for considering this feature request)

**Comment by ituligadj** [comment]
PSTV-1 Said it all!

**Comment by pthfdr-42** [comment]
I think that it should only be an option and should not be on by default.
The problem is that PSP/PSX titles' bubbles look strange on the home screen, and it can make the home screen messy.
